### ISSUE TITLE
1.7 识别英雄错误

### ISSUE THREAD

**Issue by YiyangWilliam** [cangzhang/champ-r#101]
**Describe the bug 详细描述**
无限火力选择洛结果识别1楼阿克尚

**Screenshots or screen record 截图或录屏**
![bug](https://user-images.githubusercontent.com/52186336/137351549-df8ba25e-0b12-4ba3-ad97-93786975ad8e.png)

**Desktop (please complete the following information) 系统环境:**
 - OS: win10 
 - Version ：10.0.19042 内部版本 19042

**Additional context 附加信息**

**Comment by cangzhang** [comment]
可以先用着 v1.1.6, 晚上我调查下

**Comment by cangzhang** [comment]
已经调查到原因，在修复中
