### ISSUE TITLE
1.8排位不出天赋弹窗

### ISSUE THREAD

**Issue by warmtips** [cangzhang/champ-r#103]
**Describe the bug 详细描述**
排位不出弹窗，从1.7开始就是

**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**
 - OS: [win10]
 - Version [21H1]

**Additional context 附加信息**

**Comment by cangzhang** [comment]
先卸载再重新安装 v.1.1.8

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.9
