### ISSUE TITLE
ARAM大乱斗天赋选择页面不显示胜率

### ISSUE THREAD

**Issue by fengziX** [cangzhang/champ-r#106]
在选人界面, 大乱斗的天赋(比如OP.GG ARAM)不显示胜率,只显示"大乱斗"三个字
其他页面都有胜率显示
希望大乱斗这个页面也能显示胜率

**Comment by alexya** [comment]
顶！有同样的需求。每次选人的时候，OP.GG ARM显示有四/五种天赋的选择方式，但是没有显示该方式的胜率。
于是，我只能把每个都应用一遍，记下哪个胜率最高，然后再点击应用那个......

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.10
