### ISSUE TITLE
台服问题

### ISSUE THREAD

**Issue by Humwq** [cangzhang/champ-r#107]
1.路径问题 
1.1 台服的装备要选择列表\Garena\Games\32775\Game\  [以下简称路径一]
选路径一，装备文件才出现在正确的位置\Garena\Games\32775\Game\Config\Champions\ 进游戏后能看见装备推荐
1.2 但是选这个列表不加载符文推荐窗口  要选\Garena\Games\32775\ [以下简称路径二]才出符文推荐
选路径二后，装备直接出现在\Garena\Games\32775\Config\Champions\ 且进游戏后没有装备推荐

2.速度问题（选路径二的情况下）
打开之后，1秒左右“”一键导出装备“”就可用了   但是这时候不出符文推荐窗口  要等30秒~1分钟左右  才能正常出符文推荐窗口;

干打开软件切换不了路劲 要等蛮久才行；选了路径一加载了装备后，切换到路径二 也是不出符文窗口(感觉就是改了路径都不行，不管路径对不对。)都需要关掉重启软件后，等一阵才行

在nga看见帖子，溯源而来，顺便反馈一下。希望越做越好 越来越好用。
感谢C大制作并分享！C大辛苦！

**Comment by Humwq** [comment]
那可以增加一个代理设置吗？
我让champ-r走我的代理路线。

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.10
