### ISSUE TITLE
net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by reunravel** [cangzhang/champ-r#11]
Unhandled Promise Rejection
Error: net::ERR_CONNECTION_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)
0.9.13版本 偶尔会报错 这是需要全程科学吗？

**Comment by cangzhang** [comment]
可以用这里的版本 https://github.com/cangzhang/champ-r/actions/runs/111474827，如果还出现类似情况请继续反馈

**Comment by reunravel** [comment]
> 可以用这里的版本 https://github.com/cangzhang/champ-r/actions/runs/111474827
> 如果还出现类似情况请继续反馈

好的，谢谢

**Comment by cangzhang** [comment]
发错链接了，是 https://github.com/cangzhang/champ-r/releases/tag/v0.9.14
