### ISSUE TITLE
 程序在后台运行 显示发生javascript错误 无法使用

### ISSUE THREAD

**Issue by qq360759781ok** [cangzhang/champ-r#110]
**Describe the bug 详细描述**

**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**

**Additional context 附加信息**

**Comment by qq360759781ok** [comment]
![Uploading JBSRAEZ5%0KLJOHS9A]7YKF.png…](
![TRZ6$R$1H 3AQE($K}Z00QB](https://user-images.githubusercontent.com/93712535/140638190-6d7929af-9fa4-4156-b52e-bc5cf6db370b.png)
)

**Comment by qq360759781ok** [comment]
![JBSRAEZ5%0KLJOHS9A 7YKF](https://user-images.githubusercontent.com/93712535/140638196-d515d45b-8059-4a06-8bf0-59eb5990d7c9.png)

**Comment by cangzhang** [comment]
可以试试新版本 https://github.com/cangzhang/champ-r/releases/tag/v1.1.10
