### ISSUE TITLE
无法拉取LOLALYTICS数据

### ISSUE THREAD

**Issue by yanjiepeng** [cangzhang/champ-r#116]
**Describe the bug 详细描述**
无法拉取LOLALYTICS数据
**Screenshots or screen record 截图或录屏**

![image](https://user-images.githubusercontent.com/11993224/142715533-628470ef-9993-4494-992a-a94a067c75c8.png)
![image](https://user-images.githubusercontent.com/11993224/142715559-44a0bf52-e4ee-4514-b567-d7c83ddf5663.png)

**Desktop (please complete the following information) 系统环境:**
windows10.0.19

**Additional context 附加信息**
进游戏就为空了

**Comment by cangzhang** [comment]
你的本地网络问题
