### ISSUE TITLE
天赋弹窗在一些情况下不会弹出。

### ISSUE THREAD

**Issue by UHD630** [cangzhang/champ-r#117]
**Describe the bug 详细描述**

天赋弹窗在一些情况下不会弹出。
以下情况无法正常弹窗：
1，重启LOL客户端之后
2，LOL客户端先开启，Champ-R后开启
3，一盘对局过后可能下一局就不会弹窗了
4，有时就算是先打开CHamp-R,也没弹窗 必须重置弹窗位置，等几秒，窗口才会显示。

我记得之前的版本，只要Champ-R只要是开启的状态下，天赋弹窗都能很快响应，希望能够及时恢复之前的功能

**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**

Windows 10 专业工作站版
21H1

**Additional context 附加信息**
向您表示诚挚的感谢！

**Comment by cangzhang** [comment]
感谢反馈, 我调查下

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.11
有问题的话请继续反馈

**Comment by cangzhang** [comment]
#119 合并在一起了
