### ISSUE TITLE
增加代理配置

### ISSUE THREAD

**Issue by cicirori** [cangzhang/champ-r#12]
大佬考虑支持一下代理不，我这的网络直连op.gg成功率很低。

**Comment by cangzhang** [comment]
可以先用 proxifier 之类的软件对 champR 配置代理哈，之后功能会慢慢加上

**Comment by Aqua-Dream** [comment]
等两年了，作者是不是忘记这回事了

**Comment by cangzhang** [comment]
现在的数据获取方式已经和 2 年之前有很大不同。现在的数据都在 cdn，基本不需要代理（除非墙把国内/国外 cdn 屏蔽掉）
