### ISSUE TITLE
是每次进入游戏就得重新打开软件吗  我每次进一局游戏  都得重开软件  管理员权限也是这样    

### ISSUE THREAD

**Issue by Berlin9357** [cangzhang/champ-r#124]
**Describe the bug 详细描述**

**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**

**Additional context 附加信息**

**Comment by sugarnine9** [comment]
你是不是开启了【开启游戏是关闭客户端】？

**Comment by cangzhang** [comment]
No needed infomation.

**Comment by Berlin9357** [comment]
> 你是不是开启了【开启游戏是关闭客户端】？

和这个有影响吗   我试试把这个关了   谢谢
