### ISSUE TITLE
作者你好，有一点小建议

### ISSUE THREAD

**Issue by chengfengpolangi** [cangzhang/champ-r#129]
> **对于 bug 报告, 如未填充以下内容, 将不予回复, 并于 1 天之内关闭**
希望在应用天赋的弹窗里面可以只显示个别装备源，例如目前我只应用了OPGG的装备源，在天赋的弹窗里其他的装备源也还在列表里，希望可以只显示OPGG装备源，其他的没应用就不在列表里就好了，希望可以采纳，感谢！！！
### 系统版本
 例如: Windows 10, 1809

**Comment by cangzhang** [comment]
Popup window would show result from ur last time selected source, so I dont think it's a problem.
