### ISSUE TITLE
我遇到了一些错误  

### ISSUE THREAD

**Issue by AbrnYa** [cangzhang/champ-r#130]
如图 编译提示错误 

![image](https://user-images.githubusercontent.com/77602247/145838650-9368789d-ab14-44c4-b00b-6f3d35a7b8c6.png)
如果屏蔽“imagemin-webp-webpack-plugin”直接打包则运行出现 无符文图标资源

![image](https://user-images.githubusercontent.com/77602247/145839248-248679fd-4b07-4e08-9fc8-3c697f3a879d.png)
请问该如何解决

**Comment by cangzhang** [comment]
Read code carefully.
