### ISSUE TITLE
点击一键导入出装会报错  几乎都提示红色未成功

### ISSUE THREAD

**Issue by Zjm-VIP** [cangzhang/champ-r#132]
> **对于 bug 报告, 如未填充以下内容, 将不予回复, 并于 1 天之内关闭**

### 详细描述(问题是什么/如何复现)
![16TYQFK{ OH58A5@}GF6L)S](https://user-images.githubusercontent.com/63843975/146719780-ae0ec352-5925-4489-9a6a-5950c060c0b2.png)

### 系统版本
 例如: Windows 10, 1809

**Comment by ericgidseg** [comment]
cdn.jsdelivr.net挂了

**Comment by ericgidseg** [comment]
全局代理

**Comment by hqwl1985** [comment]
我的也是~

**Comment by cangzhang** [comment]
可以先把 cdn.jsdelivr.net 加到代理规则里, 或者 hosts 里面添加:
```
104.16.85.20  cdn.jsdelivr.net
104.16.86.20  cdn.jsdelivr.net
104.16.88.20  cdn.jsdelivr.net
104.16.89.20  cdn.jsdelivr.net
```

**Comment by cangzhang** [comment]
![image](https://user-images.githubusercontent.com/1357073/146752029-39ccdca5-d104-4e9c-a567-4b1bc154d317.jpeg)

**Comment by 15555549980** [comment]
所以能说下具体的结局步骤吗

**Comment by cangzhang** [comment]
https://github.com/jsdelivr/jsdelivr/issues/18348#issuecomment-997777996
