### ISSUE TITLE
装备推荐OPGG-ARAM无限火力失效，v1.1.14

### ISSUE THREAD

**Issue by Begnion** [cangzhang/champ-r#134]
OPGG-ARAM无限火力失效，v1.1.14。
其他的模式都正常。
![无标题1](https://user-images.githubusercontent.com/49888864/146956425-3c54b9fc-daa1-4fea-887a-f23ef17801aa.png)

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.15
