### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by ShicYang** [cangzhang/champ-r#136]
用了一段时间opgg官方的，最近更新了不支持国服了，就找到这款软件了，使用很不错
有点小建议提一下
+ 天赋名称能否改一下，现在一长串又不好看又看不懂，opgg的那种就不错【OP.GG - 赏金猎人】/【LOL.QQ - 赏金猎人】这种
+ 天赋页面能否拖动位置，现在一直固定在同一位置动不了

感谢作者大大的更新

**Comment by FelixDai** [comment]
按住英雄头像可以移动的，首次打开应该有提示
