### ISSUE TITLE
rune window doesn't show up, if you start the program in the middle of the champ select

### ISSUE THREAD

**Issue by joemama06** [cangzhang/champ-r#137]
Normally I open champr before champ select and the rune select windows shows up when I select character

but if I'm in champ select then I open champr, the rune select window doesn't show up when I select character

I'm using win10

**Comment by cangzhang** [comment]
Will look into it, plz open ChampR before ur LoL client starts for now😂

**Comment by joemama06** [comment]
yeah I try not to forget it :D

**Comment by cangzhang** [comment]
@joemama06 You can start LoL/ChampR together with a bat file(customize paths below for your local environment):
```console
start "" "E:\games\League of Legends\LeagueClient.exe"
start "" "C:\Program Files\ChampR\ChampR.exe"
```

Click to run and LoL/ChampR will start simultaneously.

**Comment by joemama06** [comment]
it works tysm

**Comment by cangzhang** [comment]
@joemama06 hi joe, I think this build should have fix this issue. Have a try 🍺
https://github.com/cangzhang/champ-r/actions/runs/1637548405

**Comment by joemama06** [comment]
yes window rune window shows up even when I open it after champ select
I would like to close it by saying "can you also add u.gg to the data sources?"
thank you for this wonderful program
so much rune options without being littered with ads

**Comment by cangzhang** [comment]
@joemama06 Already planned, be patient😎

**Comment by joemama06** [comment]
nice 👍
