### ISSUE TITLE
新赛季更新后日常失效

### ISSUE THREAD

**Issue by UHD630** [cangzhang/champ-r#138]
**Describe the bug 详细描述**
重新设置弹窗位置后第一把能弹出，之后不弹出
**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**

**Additional context 附加信息**

**Comment by Zayia** [comment]
我也遇到这个情况了

**Comment by cangzhang** [comment]
一切正常

![image](https://user-images.githubusercontent.com/1357073/148555097-32a7a0a4-0c02-4706-abd6-3071927ee1f1.png)

**Comment by Zayia** [comment]
用最新版的champr会出现这个问题，用老版段就没事，建议用之前版本的
