### ISSUE TITLE
使用这个工具软件 会被封号么？

### ISSUE THREAD

**Issue by shakechoi** [cangzhang/champ-r#139]
感谢作者整合的各种数据源工具软件 好用全面且方便 。但是最近我被腾讯官方封了七天 理由是安全系统和数据被篡改 修改游戏客户端  是不是和这个工具有关 腾讯封禁这个软件了么？ 不知道其他人有没有这种情况

**Comment by cangzhang** [comment]
不会, 我自己用了一年多了从没被封. 不放心可以使用别的工具.

**Comment by shakechoi** [comment]
> 不会, 我自己用了一年多了从没被封. 不放心可以使用别的工具.

昨天试了一下，我这边的情况是换了一个号用这个工具玩大乱斗，依旧被封七天 。连续用这个工具被封两个号 不知道是个例误封 还是腾讯开始对这工具下手了。腾讯真蛋疼
