### ISSUE TITLE
Report error

### ISSUE THREAD

**Issue by wavehandxx** [cangzhang/champ-r#14]
![image](https://user-images.githubusercontent.com/14233230/83368799-b905dd00-a3ec-11ea-8302-b255278156a0.png)

**Comment by cangzhang** [comment]
Make sure you have installed latest version(https://github.com/cangzhang/champ-r/releases/tag/v0.9.14).

**Comment by cangzhang** [comment]
Please try the latest version(https://github.com/cangzhang/champ-r/releases/tag/v0.9.15-beta.1)
