### ISSUE TITLE
自动天赋的bug

### ISSUE THREAD

**Issue by lehaolun** [cangzhang/champ-r#140]
电脑是windows10，玩的美服lol，用的管理员模式打开的软件，天赋弹出正常不过打完一把再开一把就有很大几率弹不出天赋推荐了必须得关闭重开才会弹出，这是哪里设置的不对吗？

**Comment by cangzhang** [comment]
check here https://github.com/cangzhang/champ-r/wiki/FAQ#%E7%AC%AC%E4%B8%80%E5%B1%80%E6%B8%B8%E6%88%8F%E5%8F%AF%E4%BB%A5%E5%BC%B9%E5%87%BA%E5%A4%A9%E8%B5%8B%E5%BC%B9%E7%AA%97-%E4%B9%8B%E5%90%8E%E4%B8%8D%E5%86%8D%E5%87%BA%E7%8E%B0
