### ISSUE TITLE
win11 dav 22533.1001无法弹出窗口

### ISSUE THREAD

**Issue by q847633684** [cangzhang/champ-r#141]
> 对于 bug 报告, 如未填充以下内容, 将不予回复, 并于 1 天之内关闭

### 详细描述(问题是什么/如何复现)
   昨天更新系统后无法弹出符文配置窗口，确定是关闭了低配置机适应模式，也安装了powerShell 7 x64
### 截图/录屏
 
![image](https://user-images.githubusercontent.com/30609513/149768192-783cff8e-de43-4ee7-a9fe-e81ecc1bcaaa.png)
![image](https://user-images.githubusercontent.com/30609513/149768239-c82188cb-7d7d-47e6-b5f3-b95a10e07a74.png)
![image](https://user-images.githubusercontent.com/30609513/149768451-6848183b-f665-4b49-a5e6-e30e93e57d0c.png)
![image](https://user-images.githubusercontent.com/30609513/149769183-d5e3f369-ac82-45e6-acb6-3b54f62c345a.png)

### 系统版本 (如: Windows 10, 1809)
版本Windows 11 专业版 Insider Preview
安装日期2022/‎1/‎16
操作系统版本22533.1001
体验Windows Feature Experience Pack 1000.22533.1001.0
### 附加信息
还有如何开启dbug模式

**Comment by Begnion** [comment]
Win10 同样无法弹出，应该是游戏有改动。

**Comment by cangzhang** [comment]
腾讯 ban 掉了很多接口(外服都是正常的), 正在尝试看能不能找到解决方案

**Comment by VenetoVictoria** [comment]
我今天win10更新到了win11也遇到了同样的问题.

**Comment by VenetoVictoria** [comment]
> Win10 同样无法弹出，应该是游戏有改动。

最新版的win10应该可以弹出.

**Comment by sehau** [comment]
22000.438同样不行，美测服可以弹出

**Comment by Begnion** [comment]
> > Win10 同样无法弹出，应该是游戏有改动。
> 
> 最新版的win10应该可以弹出.

不可以，我的就是 21H2的最新版Win10（19044.1466）

**Comment by chickes** [comment]
> > > Win10 同样无法弹出，应该是游戏有改动。
> > 
> > 
> > 最新版的win10应该可以弹出.
> 
> 不可以，我的就是 21H2的最新版Win10（19044.1466）

我也不行

**Comment by hqwl1985** [comment]
> 腾讯 ban 掉了很多接口(外服都是正常的), 正在尝试看能不能找到解决方案

能抢救一下吗.

**Comment by cangzhang** [comment]
@AbrnYa 测试了一下还真是. 不过刚临时用 ws 解决了. 话说是从哪里得到的消息, 内部人士吗? 🤔

**Comment by AbrnYa** [comment]
> 

我也是联盟的爱好者也喜欢这些东西 我跟早就收藏你这个项目了

**Comment by AbrnYa** [comment]
> > 
> 
> 我也是联盟的爱好者也喜欢这些东西 我跟早就收藏你这个项目了

我不是内部人士 我也在调试中发现的 目前只有国服升级http2.0了 导致很多的东西都失效了

**Comment by AbrnYa** [comment]
> @AbrnYa测试了一下还真是.不过刚临时用 ws 解决了.话说是从哪里得到的消息, 内部人士吗?🤔

我不是内部人士 我也在调试中发现的 目前只有国服升级http2.0了 导致很多的东西都失效了

**Comment by hqwl1985** [comment]
@cangzhang 是不是可以用了啊.急需.刚需!

**Comment by cangzhang** [comment]
@hqwl1985 稍等, 正在构建

**Comment by hqwl1985** [comment]
@cangzhang 好的.好的.

**Comment by hqwl1985** [comment]
@cangzhang 打不开.放蓝奏吧!

**Comment by yaaisinile** [comment]
> @cangzhang mega打不开用了梯子下载了.我放网盘了.地址我放这里.有些朋友还是需要的 https://wwi.lanzouw.com/iED3ayyr64f

可以用了，感谢

**Comment by cangzhang** [comment]
> 大家可以先试试这个版本, 注意需要在**锁定英雄选择前打开 ChampR** (GitHub ci 一直挂, 暂时放到网盘)
> 
> [mega.nz/file/7Vwy3JxS#2FAU1neJulfMRn3F-PYzh_0jPxcZ8CikipGC_UTEkis](https://mega.nz/file/7Vwy3JxS#2FAU1neJulfMRn3F-PYzh_0jPxcZ8CikipGC_UTEkis)

构建链接: https://github.com/cangzhang/champ-r/actions/runs/1713873359

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.17-beta1
