### ISSUE TITLE
打开CHAMPR不能正常弹窗

### ISSUE THREAD

**Issue by GGYANJING** [cangzhang/champ-r#146]
> 对于 bug 报告, 如未填充以下内容, 将不予回复, 并于 1 天之内关闭

### 详细描述(问题是什么/如何复现)
打开CHAMPR不能正常弹窗，任何版本都不能弹窗
### 截图/录屏
![image](https://user-images.githubusercontent.com/98609114/151592712-b9df8969-7c70-4360-a54d-3eacce62f30a.png)

### 系统版本 (如: Windows 10, 1809)
windows7  旗舰版  SP1
### 附加信息
Framework 4.8版本 
PowerShell 已添加到环境变量

**Comment by Begnion** [comment]
Win10 21H2同样不能弹窗......17 Beta2

**Comment by cangzhang** [comment]
是不是官方原版系统？
有没有用什么杀毒软件？

**Comment by TamamaLemon** [comment]
win7需要安装KB3191566把wmf更到5.1
而且win7有几率主程序打开关闭后 再打开不显示主页面 然后cpu占用飙升 解决方法桌面快捷方式  --disable-gpu
win11没以上这些问题
但是这几个版本不管win7还是win11调用powershell的时候
powershell进程都占用CPU20%以上 风扇狂转 温度飚高
不知道为什么我也不懂代码
2代i7cpu
笔记本 双显卡

**Comment by GGYANJING** [comment]
> 是不是官方原版系统？ 有没有用什么杀毒软件？

系统是原版的，杀毒软件在打开champr之前已经进行关闭，平时是使用360。软件缓存都全部删除，重新安装，依旧还是不能打开，这应该是日志吧，对你有所帮助嘛？
[main.log](https://github.com/cangzhang/champ-r/files/7965498/main.log)
。

**Comment by Hickoo** [comment]
faq：关闭低配机器适应
