### ISSUE TITLE
无法正确拉取出装推荐

### ISSUE THREAD

**Issue by lightingtime** [cangzhang/champ-r#149]
**Describe the bug 详细描述**
only can poll LOL.QQ.com data ,can not poll OP.GG and LOLALYTICS.COM data 
**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**
 - OS: WIN11
 - Version 1.1.17

**Additional context 附加信息**

**Comment by cangzhang** [comment]
让 `cdn.jsdelivr.net` 走代理试试
