### ISSUE TITLE
国服更新版本了

### ISSUE THREAD

**Issue by 490355136** [cangzhang/champ-r#15]
应用内还停在10.11 建议加一个检测版本的功能 感谢开发者的付出

**Comment by reunravel** [comment]
+1 游戏版本更新到10.12了 应用内显示还停留在10.11

**Comment by cangzhang** [comment]
@490355136 @reunravel 
版本号从数据源网站拉取，它们未更新版本号，与 champR 没有关系。

**Comment by cangzhang** [comment]
`v0.9.15-beta.2` 已在数据源旁增加版本标识
![image](https://user-images.githubusercontent.com/1357073/86021170-6525fc80-ba5b-11ea-8c53-be2ce3e80d45.png)
