### ISSUE TITLE
最新版（1.1.18）卡巴斯基报毒

### ISSUE THREAD

**Issue by DavePlus** [cangzhang/champ-r#151]
如题

**Comment by DavePlus** [comment]
1.1.17同样

**Comment by DavePlus** [comment]
![image](https://user-images.githubusercontent.com/73422252/157228630-a7549e06-f40c-4107-ae7a-0e13a070a0b8.png)

**Comment by 7xanthus** [comment]
我这也是一样

**Comment by cangzhang** [comment]
软件没签名, 报毒是正常现象(尤其是卡巴这种误报几率很高的杀软).

觉得不放心卸载即可
