### ISSUE TITLE
1.1.18版本，国服12.5版本，推荐出装里的op.gg停留在12.05版本，游戏内有页面但无具体推荐出装，文件内显示为null

### ISSUE THREAD

**Issue by 56warmers** [cangzhang/champ-r#153]
> 对于 bug 报告, 如未填充以下内容, 将不予回复, 并于 1 天之内关闭

### 详细描述(问题是什么/如何复现)
1.1.18版本，国服12.5版本，推荐出装里的op.gg停留在12.05版本，游戏内有页面但无具体推荐出装，文件内显示为null
![图片](https://user-images.githubusercontent.com/56248947/158017190-3807c61a-a84e-4af4-9171-0c4e1c9c629e.png)

### 截图/录屏
![图片](https://user-images.githubusercontent.com/56248947/158017167-3b164107-5fe3-4975-9190-bd7ad6aa16ee.png)

### 系统版本 (如: Windows 10, 1809)
![图片](https://user-images.githubusercontent.com/56248947/158017178-367ffce3-b210-403b-83c7-604af223aab5.png)

**Comment by cangzhang** [comment]
已修复, 重新导入即可
