### ISSUE TITLE
管理员权限打开应用之后选择英雄不会弹出天赋弹窗

### ISSUE THREAD

**Issue by MTKmin** [cangzhang/champ-r#155]
系统 Win10 21H2
下载最新安装包 管理员权限打开应用之后选择英雄不会弹出天赋弹窗  重置天赋窗口也无效  重新下载安装之后也无效

**Comment by cangzhang** [comment]
发一下日志看看?  日志在安装目录下的 log 文件夹

**Comment by MTKmin** [comment]
![Snipaste_2022-03-14_14-18-52](https://user-images.githubusercontent.com/100497697/158119541-e66bde0b-9d5e-474d-95e3-8c0dfc72d593.jpg)
开发者你好 感谢你的回复 我没有在ChampR安装目录下找到Log文件夹 截图在附件

**Comment by cangzhang** [comment]
可以看下 `%appdata%/champr` 目录下的 logs 文件夹

**Comment by MTKmin** [comment]
[main.log](https://github.com/cangzhang/champ-r/files/8243759/main.log)
[main.old.log](https://github.com/cangzhang/champ-r/files/8243760/main.old.log)
[renderer.log](https://github.com/cangzhang/champ-r/files/8243761/renderer.log)
感谢你的回复，原来是这样，找到了。

**Comment by MTKmin** [comment]
非常感谢您的帮助  问题完美的解决了  之前软件一直正常使用 电脑Win11系统出现了恶性BUG 重装回Win10之后没想到环境变量出了问题 给你带来这么多问题 打扰了  再次感谢您的帮助 谢谢！
