### ISSUE TITLE
装备拉取不了了，天赋页面能出，但是一直转圈

### ISSUE THREAD

**Issue by LYLYILY** [cangzhang/champ-r#173]
装备拉取不了了，天赋页面能出，但是一直转圈

**Comment by cangzhang** [comment]
#174 

https://github.com/cangzhang/champ-r/wiki/FAQ#%E6%97%A0%E6%B3%95%E6%8B%89%E5%8F%96%E5%87%BA%E8%A3%85%E6%88%96%E5%A4%A9%E8%B5%8B

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/wiki/FAQ#%E6%97%A0%E6%B3%95%E6%8B%89%E5%8F%96%E5%87%BA%E8%A3%85%E6%88%96%E5%A4%A9%E8%B5%8B

**Comment by httpsColon** [comment]
> https://github.com/cangzhang/champ-r/wiki/FAQ#%E6%97%A0%E6%B3%95%E6%8B%89%E5%8F%96%E5%87%BA%E8%A3%85%E6%88%96%E5%A4%A9%E8%B5%8B

我是点闪电按钮，没有效果

**Comment by GrayDeprave** [comment]
如何对cdn.jsdelivr.net启用代理？

**Comment by sinkkin** [comment]
无限火力推荐符文居然没了，刚好开无限火力诶，可惜

**Comment by GrayDeprave** [comment]
> 无限火力推荐符文居然没了，刚好开无限火力诶，可惜

我倒是不打无限火力，主要这个插件可以让自己选别的英雄的时候能快速的套用一个模板；并且也比wegame的符文推荐更加好用。

**Comment by cangzhang** [comment]
@sinkkin 
![image](https://user-images.githubusercontent.com/1357073/170875286-05709594-cc15-45a5-a775-eeea743c291f.png)
![image](https://user-images.githubusercontent.com/1357073/170875290-fe5bc32b-68ed-4b93-bfce-7e6dd098b736.png)

**Comment by sinkkin** [comment]
> 无限火力推荐符文居然没了，刚好开无限火力诶，可惜

昨天晚上打无限火力，发现又回来了，很舒服
