### ISSUE TITLE
opgg-urf 符文查询失败, 装备导入失败!

### ISSUE THREAD

**Issue by lihao0324** [cangzhang/champ-r#174]
**Describe the bug 详细描述**
opgg-urf 符文查询失败, 装备导入失败!

**Screenshots or screen record 截图或录屏**
![50d7b35e1e7578f89fc7f90770a287b](https://user-images.githubusercontent.com/49888630/168807757-5a102cdf-988f-4530-9381-73794986c499.png)

**Desktop (please complete the following information) 系统环境:**
操作系统名称	Microsoft Windows 11 家庭版
版本	10.0.22000 版本 22000

**Additional context 附加信息**
无~

**Comment by cangzhang** [comment]
#173 https://github.com/cangzhang/champ-r/issues/173#issuecomment-1128807723
