### ISSUE TITLE
无限火力符文推荐没了

### ISSUE THREAD

**Issue by woshiliuxu** [cangzhang/champ-r#175]
> 对于 bug 报告, 如未填充以下内容, 将不予回复, 并于 1 天之内关闭

### 详细描述(问题是什么/如何复现)
选英雄时，opgg的无限活力符文推荐为空。
### 系统版本 (如: Windows 10, 1809)
w11

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/issues/173#issuecomment-1128807723
