### ISSUE TITLE
希望增加多符文适合的位置的中文翻译

### ISSUE THREAD

**Issue by AaronKate** [cangzhang/champ-r#18]
虽然认识英文，但是还是感觉不方便

**Comment by cangzhang** [comment]
盆友，英雄位置就那几个单词，相信自己你可以的

**Comment by AaronKate** [comment]
好吧，朋友，你开发的这个软件十分好用，如果有出装推荐那就更棒了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Al Cheung"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 晚上10:46
收件人:&nbsp;"cangzhang/champ-r"<champ-r@noreply.github.com&gt;;
抄送:&nbsp;"韦纯棵"<792945414@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cangzhang/champ-r] 希望增加多符文适合的位置的中文翻译 (#18)





 
Closed #18.

**Comment by cangzhang** [comment]
打开 ChampR 的时候点击那个巨大的蓝色按钮 **应用** 等待导入完成，就有出装推荐了

**Comment by cangzhang** [comment]
![image](https://user-images.githubusercontent.com/1357073/86020879-0bbdcd80-ba5b-11ea-9fc5-74e5c55b36a6.png)

**Comment by AaronKate** [comment]
谢了，朋友，你做的这个软件感觉好棒，你是一位大神




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Al Cheung"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 晚上10:51
收件人:&nbsp;"cangzhang/champ-r"<champ-r@noreply.github.com&gt;;
抄送:&nbsp;"韦纯棵"<792945414@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cangzhang/champ-r] 希望增加多符文适合的位置的中文翻译 (#18)

**Comment by cangzhang** [comment]
觉得不错点个 star 哦亲
