### ISSUE TITLE
V1.2.2推荐装备好像没有生效呢，在游戏里面没有推荐装备

### ISSUE THREAD

**Issue by ahehaoyu** [cangzhang/champ-r#180]
V1.2.2推荐装备好像没有生效呢，在游戏里面没有推荐装备

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/wiki/FAQ#无法拉取出装或天赋

**Comment by ahehaoyu** [comment]
@cangzhang   你好，里面的unpkg.com代理是怎么搞啊，charmpr里面的那个设置我一直都是启用的 但是也没有用

**Comment by cangzhang** [comment]
如果开启了「国内服务器」选项就不需要配置代理.

如果可以出现天赋, 并且可以应用, 但没有出装, 应该是你的安装目录选错.

**Comment by ahehaoyu** [comment]
非常感谢  我调整了下游戏路径，现在能正常出装了
