### ISSUE TITLE
v1.2.2 7月13日 opgg装备导入失败

### ISSUE THREAD

**Issue by chickesSAMA** [cangzhang/champ-r#187]
> 对于 bug 报告, 如未填充以下内容, 将不予回复, 并于 1 天之内关闭

### 详细描述(问题是什么/如何复现)
v1.2.2  7月13日  opgg装备导入失败
### 截图/录屏
![1657720248039](https://user-images.githubusercontent.com/76655262/178750252-90a7bb07-bff2-4408-9b3b-ce62d5429f1d.jpg)
### 系统版本 (如: Windows 10, 1809)
Windows11 21h2

**Comment by cangzhang** [comment]
临时解决方案:
设置 -> 关闭「使用国内数据源」

**Comment by alexya** [comment]
使用了上面的临时解决方案，
但是，#188还是存在。没有办法选取天赋。

**Comment by MTKmin** [comment]
![Images_1657800362651](https://user-images.githubusercontent.com/100497697/179024691-b86c8504-175b-42fb-b440-bc438e35bbec.GIF)
天赋无限加载转圈，情况如图所示。

**Comment by cangzhang** [comment]
@alexya @MTKmin 
关闭「使用国内数据源」, 同时给 unpkg.com 加上代理

**Comment by bwcxyk** [comment]
有没有尝试https://unpkg.zhimg.com/

**Comment by LaurenceJang** [comment]
> @alexya @MTKmin 关闭「使用国内数据源」, 同时给 unpkg.com 加上代理

我用clash怎么操作呀请问

**Comment by cangzhang** [comment]
@LaurenceJang 
把 `unpkg.com` 加入代理规则组里, 同时 clash 需要开启系统代理模式

**Comment by chickesSAMA** [comment]
> @LaurenceJang 把 加入代理规则组里， 同时冲突 需要开启系统代理模式`unpkg.com`

那请问我用的是v2rayn怎么代理 unpkg.com

**Comment by LaurenceJang** [comment]
> @LaurenceJang 把 `unpkg.com` 加入代理规则组里, 同时 clash 需要开启系统代理模式

谢谢回复，但是我还是没配置上，不过好消息是我关闭了国内服务器获取就解决问题了，希望其他相同问题的人可以看到我这条

**Comment by XiaobaiLi0** [comment]
为什么好久不更新了呀

**Comment by weifengze** [comment]
使用国内数据源就好了

**Comment by cangzhang** [comment]
大家可以试用一下船新的测试版本
https://github.com/cangzhang/champ-r/actions/runs/2695280174

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.3.0

**Comment by Aqua-Dream** [comment]
能不能和装备一样加上导入到本地的功能？其实版本变化符文不会差多少，但是数据源真的很不稳定。
