### ISSUE TITLE
选取英雄后，天赋推荐栏一直加载，转圈

### ISSUE THREAD

**Issue by 1405308186** [cangzhang/champ-r#188]
选取英雄后，天赋推荐栏一直加载，转圈   
伴随出现的问题：长时间等待其加载后LOL会出现网络异常

### 截图/录屏
![QQ截图20220714124423](https://user-images.githubusercontent.com/58263178/178901482-7b266a60-4a19-4637-80d3-031bb53cec2f.png)

### 系统版本 
WIN10 21H2

**Comment by cangzhang** [comment]
#187
