### ISSUE TITLE
1.2.2版本正常使用，更新1.3版本后软件打不开

### ISSUE THREAD

**Issue by Kaleo5533** [cangzhang/champ-r#194]
> 对于 bug 报告, 如未填充以下内容, 将不予回复, 并于 1 天之内关闭

### 详细描述(问题是什么/如何复现)
软件打不开，各种方法都试了
### 截图/录屏
1.2.2版本程序界面
![1 2 2版本](https://user-images.githubusercontent.com/56016301/180658315-a2e41c63-d343-4522-aaa9-c7ff77428d24.png)
1.2.2版本符文界面
![1 2 2符文](https://user-images.githubusercontent.com/56016301/180658327-f4d187ae-a89d-4f5e-87c9-b4ea8bcc0d06.png)
1.3版本打不开
![1 3版本打不开](https://user-images.githubusercontent.com/56016301/180658334-a93fd4b5-7740-4364-8dfa-391a9aa43cf8.png)

### 系统版本 (如: Windows 10, 1809)
![系统](https://user-images.githubusercontent.com/56016301/180658365-d53fdd1b-76d4-457b-897f-490503bf39c0.png)

### 附加信息
![image](https://user-images.githubusercontent.com/56016301/180658587-32db1adb-b0a6-405e-9082-f30e00cce75f.png)

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/actions/runs/2729454054

试试这个版本

**Comment by whj768** [comment]
还是用不了 测试版本1.3

**Comment by cangzhang** [comment]
@whj768 

http://ddragon.leagueoflegends.com/cdn/12.13.1/data/en_US/champion.json

这个网址可以打开吗, 不翻墙的情况下

**Comment by cangzhang** [comment]
@whj768 @Kaleo5533 

https://github.com/cangzhang/champ-r/actions/runs/2736760827

 试试这个版本, 贴一下 log 看看

**Comment by whj768** [comment]
我公司的电脑可以打开的 家里的不行

**Comment by whj768** [comment]
https://github.com/cangzhang/champ-r/actions/runs/2736760827 昨天家里试过了 这个打不开 就是双击然后跳不出来 1.2.2是正常的

**Comment by cangzhang** [comment]
@whj768 [runs/2736760827](https://github.com/cangzhang/champ-r/actions/runs/2736760827) 是我刚发的

**Comment by whj768** [comment]
@cangzhang  晚上我回家测试一下嘿嘿 然后给您反馈

**Comment by flamingocc** [comment]
我也打不开，包括这个测试也不行https://github.com/cangzhang/champ-r/actions/runs/2736760827

**Comment by cangzhang** [comment]
@flamingocc 贴一下 log 看看, `%APPDATA%/ChampR/logs/main.log`

**Comment by whj768** [comment]
我试了还是不行 只有1.2.2是好的 1.3.0任何版本包括测试版都打不开

**Comment by whj768** [comment]
@cangzhang

**Comment by cangzhang** [comment]
@whj768 用这个版本 [runs/2736760827](https://github.com/cangzhang/champ-r/actions/runs/2736760827), 贴一下 log
https://github.com/cangzhang/champ-r/issues/194#issuecomment-1195450924

**Comment by whj768** [comment]
log咋贴

**Comment by whj768** [comment]
![Uploading image.jpg…]()

**Comment by Kaleo5533** [comment]
@cangzhang [runs/2736760827](https://github.com/cangzhang/champ-r/actions/runs/2736760827) 这个测试版还是打不开
![image](https://user-images.githubusercontent.com/56016301/181138139-8e9cc956-945b-47f6-a3e1-6fa0c07815a2.png)

**Comment by cangzhang** [comment]
@Kaleo5533 
可以试试这个 https://github.com/cangzhang/champ-r/actions/runs/2743929992

**Comment by Kaleo5533** [comment]
@cangzhang 这个版本https://github.com/cangzhang/champ-r/actions/runs/2743929992依旧不行，打不开
![image](https://user-images.githubusercontent.com/56016301/181164424-607ae3b8-78af-46aa-ab2d-06d21b4eed11.png)

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/actions/runs/2744362528

先把之前的卸载了, 再安装.

另外, 你的 Windows 是官方原版吗?

**Comment by Kaleo5533** [comment]
每次都是卸载重新安装的，是官方原版，前段时间更新win11之后，回退了一次，不清楚是不是这个原因
https://github.com/cangzhang/champ-r/actions/runs/2744362528 @cangzhang 这个版本可以正常打开了，谢谢
![image](https://user-images.githubusercontent.com/56016301/181208524-1fd3122d-c755-4df0-92ac-6a2e056dbd1e.png)

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.3.1

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/issues/191
