### ISSUE TITLE
符文选择列表无法拖拽在窗口的位置

### ISSUE THREAD

**Issue by zzsuki** [cangzhang/champ-r#197]
> 对于 bug 报告, 如未填充以下内容, 将不予回复, 并于 1 天之内关闭

### 
![image](https://user-images.githubusercontent.com/57662555/181865500-22c81683-67d8-4590-b438-64a584b01885.png)

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/wiki/FAQ
