### ISSUE TITLE
装备文件未按数据源顺序排序

### ISSUE THREAD

**Issue by Wasshoiiiiii** [cangzhang/champ-r#198]
**Describe the bug 详细描述**
装备文件未按数据源顺序排序

**Screenshots or screen record 截图或录屏**
![排序1](https://user-images.githubusercontent.com/52164290/182030340-ed7a727a-9307-4e10-be24-de6ca3b9b624.png)

**Desktop (please complete the following information) 系统环境:**
 - OS: [win10 21H2]
 - Version [v1.3.2]

**Additional context 附加信息**
v1.2.2那时是正常的
![排序2](https://user-images.githubusercontent.com/52164290/182031173-35d6115f-65e6-4e20-8a90-e1fb30236737.png)

**Comment by whj768** [comment]
两个建议 能否提示康特英雄 还有召唤师技能 比如闪现 点燃这些谢谢

**Comment by whj768** [comment]
@cangzhang

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.3.3
