### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by ruifengzhai** [cangzhang/champ-r#2]
开发者您好，我觉得您的文档可以写的清晰一点，比如说一是开发需要环境以及开发操作指南；二是食用指南以及一些待优化的点。
最后我希望你把捐献码贴出来，这个APP我用了，我觉得比wegame的舒服多了，虽然有很多待完善的地方，但我很喜欢，希望您可以坚持下去，我也希望我可以为您的这个产品出一份力。

**Comment by cangzhang** [comment]
感谢支持。
1. 开发说明对一个开发者来说已经足够了。任何开发环境都没有问题，只要安装了里面说的依赖。
2. 后续会给 readme 加上 roadmap
3. 目前不会接受任何捐赠。
