### ISSUE TITLE
英雄选择界面，天赋配置页面空白

### ISSUE THREAD

**Issue by flamingocc** [cangzhang/champ-r#200]
英雄选择界面，天赋配置页面空白

![微信截图_20220813125051](https://user-images.githubusercontent.com/35923915/184469035-b9c03c38-48f5-43ea-97d7-5b0abae503e3.png)

系统版本 ：Win10

**Comment by flamingocc** [comment]
有时候选第一个英雄会跳出页面（几率很低），但选第二个后就直接白了。
是白了，没有显示加载的页面哦。

**Comment by cangzhang** [comment]
试试删除 `%appdata%/ChampR/config.json` 文件

**Comment by duzhor** [comment]
> 试试删除 `%appdata%/ChampR/config.json` 文件

删除之后正常出现了两三次然后又不行了

**Comment by duzhor** [comment]
完全卸载并删除后，重新安装，不调整装备顺序，似乎天赋弹窗正常工作。怀疑可能跟装备顺序有关

**Comment by flamingocc** [comment]
能恢复，但我依次切换装备数据源后，到U.GG-ARAM就又白屏了，不知道有没有关系。

**Comment by duzhor** [comment]
重新测试了下删除config.json后恢复正常，只要不选择U.GG-ARAM就能正常使用，可能确实跟这个有关

**Comment by Aqua-Dream** [comment]
一个建议，网络加载符文卡顿的时候，至少把源先显示出来，这样如果OP.GG加载不出来，至少可以换LOL.QQ.COM作为备用方案。

**Comment by cangzhang** [comment]
大部分情况下的问题应该都已经得到解决, 大家可以重新试试 `u.gg-aram` 数据源(重新导入数据, 或在天赋窗口切换到该 option).
