### ISSUE TITLE
[watcher] fetch lcu status failed

### ISSUE THREAD

**Issue by LaurenceJang** [cangzhang/champ-r#212]
> 对于 bug 报告, 如未填充以下内容, 将不予回复, 并于 1 天之内关闭
请问下这个错误是什么意思
### 详细描述(问题是什么/如何复现)
使用bat登录后 应该是新增了获取更新的功能，自动去读取了最新的版本，但是后面就一直报这个错误，我本来以为是网络问题，挂了梯子还是不行，
### 截图/录屏
![捕获](https://user-images.githubusercontent.com/65761869/189588942-02cef87e-8d1d-4053-b765-408b69396ee8.JPG)

### 系统版本 (如: Windows 10, 1809)
win10

**Comment by cangzhang** [comment]
如果没有启动 lol 的话，会提示该信息，属于正常 log
