### ISSUE TITLE
CPU占用间断性增高

### ISSUE THREAD

**Issue by zhaoliang0302** [cangzhang/champ-r#214]
**Describe the bug 详细描述**
间断性出现powershell的进程，占用比较高，但是马上会消失再出现，一直间断有，不会停

**Screenshots or screen record 截图或录屏**
![image](https://user-images.githubusercontent.com/42333702/191172065-51543868-f0f3-4309-a498-0215a38fbcfe.png)

**Desktop (please complete the following information) 系统环境:**
 - OS: windows 10
 - Version 1809

**Comment by hkthomas** [comment]
老早反应过这问题了，你还间歇性，我持续性。6700k，就光champr进程15-30%的占。

**Comment by zhaoliang0302** [comment]
> 老早反应过这问题了，你还间歇性，我持续性。6700k，就光champr进程15-30%的占。

我这是间断几秒就会高占用，整个过程一直这么跳
