### ISSUE TITLE
[Bug]自动点天赋失效了

### ISSUE THREAD

**Issue by TingYhan** [cangzhang/champ-r#215]
**Describe the bug 详细描述**
在点击应用天赋没有效果。

**Desktop (please complete the following information) 系统环境:**
 - OS: [win11 22H2]
 - Version [22621.521]

**Comment by waycowei** [comment]
+1

**Comment by waycowei** [comment]
- Windows 11 OS [22622.598]

**Comment by cuthx** [comment]
+1

**Comment by Fabali** [comment]
应该是接口失效了吧，我看好多辅助工具都失效了

**Comment by prisonninja** [comment]
+1

**Comment by newblas3** [comment]
+1

**Comment by chickesSAMA** [comment]
+1

**Comment by sexchen** [comment]
+1 不过有时可以

**Comment by Pauluooooo** [comment]
+1

**Comment by tanxianjiaa** [comment]
+1

**Comment by fancyteo** [comment]
+1

**Comment by GGjin** [comment]
+1

**Comment by wl1320310292** [comment]
me too

**Comment by LaurenceJang** [comment]
+1，

**Comment by Jeffrey0418** [comment]
+1

**Comment by 1909490139** [comment]
+1

**Comment by fatesealed** [comment]
+1

**Comment by anakin777** [comment]
这是马服作妖

**Comment by alexya** [comment]
确实，我这边也发现失效了！只能手点......

**Comment by Zjm-VIP** [comment]
+1 希望作者尽快修复

**Comment by Yukino-Yukinosita** [comment]
+1 我这里也失效了

**Comment by whj768** [comment]
我也失效了

**Comment by HayBranch** [comment]
有修复的机会吗

**Comment by csmczconzns** [comment]
+1,昨天刚发现的

**Comment by csmczconzns** [comment]
+1，昨天刚发现的，可能是跟随12.18更新更改了接口。

**Comment by lbjg0at** [comment]
https://t.me/c/1200370923/1058

仅供参考

**Comment by Fabali** [comment]
> https://t.me/c/1200370923/1058
> 
> 仅供参考

不行，提示我没在这个群组里面，打不开

**Comment by xxbash** [comment]
> https://t.me/c/1200370923/1058
> 
> 仅供参考

不在群组内打不开

**Comment by lbjg0at** [comment]
https://t.me/champ_r/67

评论里翻一下
![image](https://user-images.githubusercontent.com/71868137/192147877-dcf2d860-cf5f-4c8d-a317-41c061e22003.jpeg)

**Comment by cangzhang** [comment]
目前收到反馈可行的一个方案：

1. 下载体验服转换器
2. 转换为体验服
3. 登陆账号，进入游戏大厅，退出
4. 转换回正式服

就可以正常使用了。

![image](https://user-images.githubusercontent.com/1357073/192153277-a53a8d62-52c9-4c02-8df6-69a658178706.png)

**Comment by pistoolster** [comment]
试了下确实可以了

**Comment by chickesSAMA** [comment]
登录体验服需要wegame开启但是没有体验服账号咋搞，官网也看不见体验服申请

**Comment by Yukino-Yukinosita** [comment]
> ```
> <Server> 
>     <DirServer count="1" SuccessfulServerID="1" SuccessfulPort="5223"> 
>         <server1 host="tdir-test.lol.qq.com" /> 
>         <portlist count="1" port1="5223">0</portlist> 
>     </DirServer> 
> </Server>
> ```

谢谢大佬，非常有效果

**Comment by MoeGakuen** [comment]
体验服似乎维护了

**Comment by sxzcy** [comment]
> > 登录体验服需要wegame开启但是没有体验服账号咋搞，官网也看不见体验服申请
> 
> 删除 `英雄联盟安装目录/TCLS/` 目录下的：
> 
> * `wegame_launch.tmp`
> * `WGTinyDL.dll`
> * `WGTinyDL.exe`
> 
> 3个文件，然后点击`Client.exe`即可绕过 WeGame 登录体验服。

删了之后下载不了了，卡启动界面

**Comment by Crikey9** [comment]
能显示，点了没反应+1

**Comment by sunFlying** [comment]
进体验服，注册了新账号，显示游戏崩溃了
让等5:30；然后时间也不走秒。。。

**Comment by sunFlying** [comment]
> 进体验服，注册了新账号，显示游戏崩溃了 让等5:30；然后时间也不走秒。。。

这个并不影响，退出换回正式服就可以了。
感谢方案

**Comment by Pauluooooo** [comment]
这个还能修好吗，，还是说都只能这样了。
