### ISSUE TITLE
V1.3.6

### ISSUE THREAD

**Issue by chickesSAMA** [cangzhang/champ-r#216]
我看不能应用天赋的解决办法需要登录体验服，登录体验服需要wegame开启但是没有体验服账号咋搞，官网也看不见体验服申请

Win11 21H2

**Comment by cangzhang** [comment]
你自己随便搜搜就能搜到, 正式服任一大区满 30 级就可以用自己的 qq 登陆体验服.
另外, 和 ChampR 无关的问题不要发在 issues 里
