### ISSUE TITLE
一键天赋只能用一次，后面弹出天赋界面也能获取到内容但是点击没反应

### ISSUE THREAD

**Issue by ws34586** [cangzhang/champ-r#218]
一键天赋只能用一次，后面弹出天赋界面也能获取到内容但是点击没反应

**Comment by TingYhan** [comment]
今天又用不了了

**Comment by alexya** [comment]
me too

**Comment by yzlyu** [comment]
> 点了没反应的再改一次体验服再改回去就可以了

我也没弄过体验服啊

**Comment by TingYhan** [comment]
> 点了没反应的再改一次体验服再改回去就可以了

我是换另一个账号登录体验服再改回正式服是没反应的，换回原来能用的号又好使了。。。

**Comment by moyifan** [comment]
> > 点了没反应的再改一次体验服再改回去就可以了
> 
> 我是换另一个账号登录体验服再改回正式服是没反应的，换回原来能用的号又好使了。。。

改到体验服直接用训练模式试试  可以的话马服也可以

**Comment by moshuying** [comment]
这个bug不会无解吧

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.3.7
