### ISSUE TITLE
"一键导入出装"功能建立乱码文件夹

### ISSUE THREAD

**Issue by hookbin** [cangzhang/champ-r#230]
**Describe the bug 详细描述**
"一键导入出装"功能建立乱码文件夹
游戏文件夹层级为`D:\tencent\LOL\英雄联盟`
乱码文件夹层级为`D:\tencent\LOL\鑻遍泟鑱旂洘\Game\Config\Champions`

**Screenshots or screen record 截图或录屏**
![image](https://user-images.githubusercontent.com/13349733/197333308-2f8a4617-91b6-4a42-931d-1d13bd494c9d.png)
![image](https://user-images.githubusercontent.com/13349733/197333319-7ea4e8a7-bcbe-45cb-840c-d18df50f0bb7.png)

**Desktop (please complete the following information) 系统环境:**
 - OS: Windows10
 - Version v1.3.11

**Comment by hookbin** [comment]
乱码文件夹层级为

**Comment by cangzhang** [comment]
马服特色
