### ISSUE TITLE
是不更新了嘛

### ISSUE THREAD

**Issue by LaurenceJang** [cangzhang/champ-r#252]
rt
是不更新了嘛

**Comment by Echo0ff** [comment]
好像是的

**Comment by LaurenceJang** [comment]
我看好像是接口关闭获取不到游戏没信息了，好像目前还没解决方案，唉，可惜-------- 原始邮件 --------发件人： 佳伟 ***@***.***>日期： 2023年2月28日周二 13:48收件人： cangzhang/champ-r ***@***.***>抄送： LaurenceJang ***@***.***>, Author ***@***.***>主    题： Re: [cangzhang/champ-r] 是不更新了嘛 (Issue #252)

好像是的

**Comment by Echo0ff** [comment]
国服今天更新了又可以用了

**Comment by LaurenceJang** [comment]
> 国服今天更新了又可以用了

我这并没有可以用。。

**Comment by MasterOfStar** [comment]
国服上上次更新把lcu的限制打开了，就不能用了。上次更新又关了，就又可以用了

**Comment by BAIuyu** [comment]
> 国服上上次更新把lcu的限制打开了，就不能用了。上次更新又关了，就又可以用了

但是我现在不管是v1还是v2 两个版本都不能用 反而 日服那里是能用的（（

**Comment by LaurenceJang** [comment]
不行，马服我这还是不能用。。。

**Comment by MasterOfStar** [comment]
> > 国服上上次更新把lcu的限制打开了，就不能用了。上次更新又关了，就又可以用了
> 
> 但是我现在不管是v1还是v2 两个版本都不能用 反而 日服那里是能用的（（

我这边马服已经能用了，v1在我本机和网吧的机子上都是能用的。同类软件如leaguetavern也是可以用的。
其他的用lcuAPI的软件比如leaguelobby也没问题。

**Comment by BAIuyu** [comment]
> > > 国服上上次更新把lcu的限制打开了，就不能用了。上次更新又关了，就又可以用了
> > 
> > 
> > 但是我现在不管是v1还是v2 两个版本都不能用 反而 日服那里是能用的（（
> 
> 我这边马服已经能用了，v1在我本机和网吧的机子上都是能用的。同类软件如leaguetavern也是可以用的。 其他的用lcuAPI的软件比如leaguelobby也没问题。

leaguetavern我也能用 就是这个不能用 昨天我都修复一次游戏资源了 还是不能用）

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v2.0.0
