### ISSUE TITLE
4k分辨率下软件失效

### ISSUE THREAD

**Issue by biankobe24** [cangzhang/champ-r#29]
RT，更新了之后4K用不了了，除非要忽略系统缩放才行

**Comment by cangzhang** [comment]
我自己没有复现出这个问题, 而且我自己用的也是 4k.
更新到最新版本之后, 试试点击主界面上的‘重置天赋弹窗位置’?

**Comment by biankobe24** [comment]
> 我自己没有复现出这个问题, 而且我自己用的也是 4k.
> 
> 更新到最新版本之后, 试试点击主界面上的 `重置天赋弹窗位置` ?

thank u，更新到最新的没问题了，之前一直弹不出来
