### ISSUE TITLE
请问有没有log呢

### ISSUE THREAD

**Issue by xymeng16** [cangzhang/champ-r#3]
选好lol目录，导入两个网站的数据之后，一直无法在游戏内找到champr的界面。。想看看log是哪里出了问题

**Comment by cangzhang** [comment]
需要推荐天赋的话需要保持 ChampR 打开。
log 在 `%USERPROFILE%\AppData\Roaming\champ-r\logs\renderer.log` 目录下

**Comment by cangzhang** [comment]
一定记得「以管理员身份运行」
