### ISSUE TITLE
数据服务端Cloud Flare回源失败

### ISSUE THREAD

**Issue by Lz1y** [cangzhang/champ-r#305]
https://github.com/cangzhang/champ-r/blob/47fe3110b8a311a693cc310d12f20e3b6b751559/src/web.rs#L14

请求服务端拉取数据时，回源失败：
https://ql-rs.lbj.moe/api/sources
![图片](https://github.com/cangzhang/champ-r/assets/23468993/7f0ae3b2-dbbf-4771-a4b1-1b4b13a45c63)

疑似服务端异常，已经持续三天左右时间了。

**Comment by cangzhang** [comment]
感谢反馈, 我看一下服务器

**Comment by Lz1y** [comment]
> 感谢反馈, 我看一下服务器

好的，此前访问是返回500错误，换了不同节点也是此结果。另外，谢谢您的工具，非常好用。

**Comment by cangzhang** [comment]
Hi @Lz1y, 服务已经重新上线了, 你需要本地刷新下 dns 并重启 ChampR, 不行的话可以试试重启电脑

![image](https://github.com/cangzhang/champ-r/assets/1357073/01272da8-7960-4caa-a4a7-66efb29809d1)

**Comment by Lz1y** [comment]
@cangzhang 测试已经可用，感谢你
