### ISSUE TITLE
符文和出装版本过时

### ISSUE THREAD

**Issue by ws34586** [cangzhang/champ-r#306]
目前软件推荐的天赋与对应原网站上的推荐天赋不同步 
如： 我选择石头人目前opgg上推荐的是不灭  但是不管我是用V2版本还是V1版本 显示推荐天赋均为彗星 
![Uploading 1fe8a1b94931d48c475e0f4438d51265.png…]()

**Comment by ws34586** [comment]
![1fe8a1b94931d48c475e0f4438d51265](https://github.com/cangzhang/champ-r/assets/66230396/24df3fb8-eb44-4b2b-b321-48f945c8b82a)

**Comment by ws34586** [comment]
![2318a2244e31a0183cdc1fdb451f467f](https://github.com/cangzhang/champ-r/assets/66230396/5f117db3-0500-4637-907b-2c46638154c7)

**Comment by cangzhang** [comment]
感谢反馈, 我会调查下这个问题
