### ISSUE TITLE
一个图标启动游戏和ChampR

### ISSUE THREAD

**Issue by ningbowang** [cangzhang/champ-r#36]
留给后来人查看，希望作者不介意

# 一、一键打开LOL和CharmpR： 

1. 安装CharmpR
2. 批处理文件内容：

```powershell
@echo off
chcp 65001 
start "" "D:\WeGame\英雄联盟\TCLS\Client.exe"
start "" "C:\Users\18736\AppData\Local\Programs\champ-r\ChampR.exe"
```

在桌面新建文本文档，复制上述内容到文本文档（注意改成自己的  游戏路径 和 champR路径），保存退出 后缀改成  `.bat`  （例如 一键多开.bat），双击文件就能同时启动这两个软件

3. 创建.bat文件的快捷方式（此时快捷方式改成想要的名字，后续还想固定到开始屏幕的话不好设置）

# 二、快捷方式美化： 

1. 设置图标样式： 右键快捷方式->属性->更改图标->就可以选择图标了(.ico格式的图片)

> 官方图标位置在（英雄联盟安装路径\英雄联盟\TCLS\ui\res\Icon.ico）			
> 例如：D:\WeGame\英雄联盟\TCLS\ui\res\Icon.ico

2. 固定到开始屏幕：

- win10: 快捷方式拖入 C:\ProgramData\Microsoft\Windows\Start Menu\Programs 路径下，就能从开始菜单中找到该快捷方式，右键“固定到开始屏幕”了
- win11: 快捷方式拖入 C:\ProgramData\Microsoft\Windows\Start Menu\Programs 路径下，再按 win徽标键 -> 所有应用 ->找到你自己的快捷方式名字 如`一键多开.bat` ， 右键“固定到开始屏幕”

**Comment by h954156330** [comment]
可以可以，我一开始也这么干过。都来都是CharmpR开机自启了哈哈哈哈哈
