### ISSUE TITLE
qq和opgg在没打开lol情况下导入失败 

### ISSUE THREAD

**Issue by woshinibb66** [cangzhang/champ-r#39]
qq和opgg在没打开lol情况下导入失败

**Comment by woshinibb66** [comment]
未成功: LOL.QQ.COM
[OP.GG] 未成功: 1
Viego

**Comment by cangzhang** [comment]
只是 Viego 这个英雄未成功, 不是所有都失败了.
因为 op.gg 还没有更新这个英雄的数据.

**Comment by woshinibb66** [comment]
lolqq的也没成功还是11。1的
