### ISSUE TITLE
能不能把那个给推荐的界面缩小一点，现在这个太大了

### ISSUE THREAD

**Issue by wang-zh** [cangzhang/champ-r#4]

**Comment by ruifengzhai** [comment]
我觉得可以就一个英雄头像，鼠标放上之后，再把详细的放大，鼠标移走就变回一个头像

**Comment by cangzhang** [comment]
弹窗很大的话应该是你开了系统缩放吧？可以单独对程序设置

Win10 下如何单独给程序设置 DPI 缩放？ - 烤榴莲好吃的回答 - 知乎
[https://www.zhihu.com/question/54913665/answer/1075538175]
