### ISSUE TITLE
希望作者大佬能够适配外服

### ISSUE THREAD

**Issue by UHD630** [cangzhang/champ-r#42]
我是一名韩服和日服的低分玩家，大部分时间都在外服，希望能够适配。软件非常好已推荐给朋友

**Comment by cangzhang** [comment]
韩, 日服在 [>= 1.0.2](https://github.com/cangzhang/champ-r/releases/tag/v1.0.2) 版本都已经支持了, 我们的群友都测试过了, 你也可以测试一下. 注意等级比较低的号是没有符文可以设置的, 没有天赋推荐, 所以**需要等级比较高的号才行**
