### ISSUE TITLE
一些建议 Some suggestions

### ISSUE THREAD

**Issue by sugarnine9** [cangzhang/champ-r#43]
我又来啦，距离我上一次提出建议我上一次提出建议已经过去好久了。感觉上一次我提出的意见，作者大部分都做到了。所以现在来提出一些新的意见。
我看OPGG上面有推荐召唤师技能和推荐英雄技能加点，不知道开发者能不能做出来，可能玩新英雄或者大乱斗随机到没玩过的英雄的时候需要。当然这个功能的优先级也不是那么高，也不是那么必须要做。
再次感谢作者！谢谢！
Mechanical translation：
I'm here again. It's been a long time since I made my last suggestion. I feel that most of the opinions I put forward last time have been achieved. So let's put forward some new ideas.
In my opinion, opgg has recommended Summoner skills and recommended hero skills. I don't know if developers can do it. It may be needed when playing new heroes or fighting randomly to heroes they haven't played before. Of course, the priority of this function is not so high, and it is not so necessary.
Thanks again to the author! thank you!

**Comment by Tr3c3** [comment]
Regarding hero skills, usually build-importing tools have the skill leveling order / maxing priority (Q > E > W) as item group names.

**Comment by cangzhang** [comment]
We have added skills order to `op.gg` source(`Summoner's Rift`/`ARAM`/`URF`), and will implement this for other sources later.
