### ISSUE TITLE
希望大佬能添加LOLALYTICS的数据源

### ISSUE THREAD

**Issue by wuif96** [cangzhang/champ-r#45]
https://lolalytics.com/

如果能加入召唤师技能推荐就更好了

**Comment by JLYShirley** [comment]
对！！！求大佬加上这个！！！

**Comment by woshinibb66** [comment]
看着不错

**Comment by cangzhang** [comment]
会在接下来加上

**Comment by cangzhang** [comment]
最近几天会发布, 记得先更新到最新版本 https://github.com/cangzhang/champ-r/releases

**Comment by wuif96** [comment]
好耶

**Comment by cangzhang** [comment]
已发布 https://github.com/cangzhang/champ-r/releases/tag/v1.1.2
