### ISSUE TITLE
不起作用

### ISSUE THREAD

**Issue by beifeng5620** [cangzhang/champ-r#5]
LOL路径如下：
F:\Program Files\腾讯游戏\英雄联盟

**Comment by cangzhang** [comment]
请按以下内容描述具体的现象，能够附上截图最好。

- 系统版本
- 是否以管理员权限运行？
- 能否导入推荐出装？
- 能否显示推荐天赋？
- 请附上日志 (`%USERPROFILE%\AppData\Roaming\ChampR\logs\renderer.log`)

**Comment by beifeng5620** [comment]
谢谢JR！问题已解决，以管理员身份运行即可，不然只有推荐出装
