### ISSUE TITLE
程序出错

### ISSUE THREAD

**Issue by LeopoldChou** [cangzhang/champ-r#52]
在国服客户端，WeGame 启动的 11.7 游戏版本下无法弹窗，已经是以管理员身份运行，重置天赋弹窗位置，重启应用和重启电脑均无法解决该问题。

**Comment by cangzhang** [comment]
我本地测试是没有问题的。你可以试试卸载后再重新安装

**Comment by LeopoldChou** [comment]
卸载了，重新安装了，天赋窗口仍然弹不出来。
如何清除 Champ-R 所有的数据？因为我 Uninstall 之后再装，所有的以前的设置都留下来了，我想知道他都往系统哪些地方写了数据，我全部删掉试一下。

**Comment by cangzhang** [comment]
@LeopoldChou 在 %APPDATA% 下面, 尝试搜索 `ChampR`

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.1
