### ISSUE TITLE
下载最新版本为什么选择英雄没反应呢？

### ISSUE THREAD

**Issue by zoubeihua** [cangzhang/champ-r#62]
**Describe the bug 详细描述*
选择游戏目录后一键导入，打开游戏登陆选择英雄后怎么没有推荐符文的窗口呢？有没有使用教程呢？貌似我用这个导入之后，接下来完全是懵的，也没有提示什么快捷键之类的呼出符文窗口？网上也搜索不到教程，我也是用管理人员权限打开的，

**Desktop (please complete the following information) 系统环境:**
 - OS: win10

**Comment by cangzhang** [comment]
lol 目录选对了吗？
贴上来日志看看？

**Comment by zoubeihua** [comment]
> lol目录选对了吗？
> 贴上来日志看看？

选的是TCLS这个目录

**Comment by cangzhang** [comment]
@zoubeihua 选错目录了, 选到 英雄联盟 那个文件夹就行了.
仔细看看目录下面的那个示例

**Comment by zoubeihua** [comment]
> @zoubeihua 选错目录了, 选到 英雄联盟 那个文件夹就行了.
> 仔细看看目录下面的那个示例

好的。谢谢
