### ISSUE TITLE
一键启动 ChampR + WeGame/LOL

### ISSUE THREAD

**Issue by cangzhang** [cangzhang/champ-r#63]
1. 桌面新建文件 `启动lol.bat`
1. 编辑文件，添加以下内容
> ⚠️**自行替换路径为你的系统中的应用路径**
```
start "" "C:\games\WeGameLauncher\launcher.exe" 
start "" "C:\Programs Files\ChampR\ChampR.exe"
```
如果你需要直接启动 lol 客户端，向以上文件中添加以下内容：
```
start "" "C:\games\lol-cn\TCLS\Client.exe"
```
3. 双击运行 `启动lol.bat`

**Comment by sugarnine9** [comment]
牛啊！

**Comment by xiaobaiEzrea** [comment]
1.如果开了系统自带的防火墙，会让你自己进行确认登录，重复确认。如何进行一次到位，直接打开两个软件？？
2.lol客户端每次打开都要重新输入密码（不用wegame），请问怎么解决这个问题，自动保存密码，效果如为game一样，纯小白。指导思路即可

**Comment by Fabali** [comment]
start "" "C:\Users\{username}\AppData\Local\Programs\champ-r\ChampR.exe"运行这个之后出现
23:53:57.866 > ChampR starting...
23:53:58.044 > locale: zh-CN, sys lang: zh-CN
23:53:58.934 > userId: 1b339feca8cb0570078c682b801e0f8cf3ab7c5d89f6dda29649ed4e721018be
23:53:58.935 > Checking for update
23:53:58.936 > Checking update...
23:54:03.214 > Update for version 1.1.4 is not available (latest version: 1.1.4, downgrade is disallowed).
23:54:03.215 > Update not available: 1.1.4
然后网络检查失败，这个导致窗口关闭后ChampR就自动关闭了，怎么解决？
