### ISSUE TITLE
天赋弹窗没有办法拖动

### ISSUE THREAD

**Issue by he429134733** [cangzhang/champ-r#69]
天赋弹窗没有办法拖动，请问原本是可以拖动的么。。
![image](https://user-images.githubusercontent.com/44768024/129445485-57f1de4f-e6ae-4d59-9fbd-8af9eb164768.png)
一直是再这个位置，重置了还是在这个位置，没有办法拖动到其他地方，体验有点不好

**Comment by cangzhang** [comment]
按住头像拖动

**Comment by he429134733** [comment]
好的感谢！
