### ISSUE TITLE
建议写一篇代码架构文章

### ISSUE THREAD

**Issue by dirkhe1051931999** [cangzhang/champ-r#70]
**Describe the bug 详细描述**
比如框架（electron）与nodejs或者go的交互和联调

**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**

**Additional context 附加信息**

**Comment by cangzhang** [comment]
electron 应用的架构比较简单, 因为主要的东西都在它内部做了. 
上层应用的架构大体都是这个样子, 有兴趣的话可以多搜搜文章学习
