### ISSUE TITLE
lol更新以后不会弹天赋窗了

### ISSUE THREAD

**Issue by bakamoon** [cangzhang/champ-r#81]
**Describe the bug 详细描述**
lol更新以后不会弹天赋窗了，一直使用的是1.0.3的版本，1.0.3的版本会弹出主界面更新装备，但是不会弹出天赋窗，1.0.3之后的版本安装后主界面不会弹出无法使用

**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**
win10系统

**Additional context 附加信息**

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.4
