### ISSUE TITLE
关于bat脚本一键启动这个软件

### ISSUE THREAD

**Issue by Fabali** [cangzhang/champ-r#84]
https://github.com/cangzhang/champ-r/issues/63#issue-898134786
这个链接里面，我用bat脚本启动之后，提示：
23:53:57.866 > ChampR starting...
23:53:58.044 > locale: zh-CN, sys lang: zh-CN
23:53:58.934 > userId: 1b339feca8cb0570078c682b801e0f8cf3ab7c5d89f6dda29649ed4e721018be
23:53:58.935 > Checking for update
23:53:58.936 > Checking update...
23:54:03.214 > Update for version 1.1.4 is not available (latest version: 1.1.4, downgrade is disallowed).
23:54:03.215 > Update not available: 1.1.4
还关不掉，一会儿就提示网络错误了，怎么关闭这个东西

**Comment by cangzhang** [comment]
网络错误是你的本地网络无法访问 github 导致的，和通过 bat 启动没有关系。

**Comment by Fabali** [comment]
> 网络错误是你的本地网络无法访问 github 导致的，和通过 bat 启动没有关系。

这个可以关闭吗？
