### ISSUE TITLE
LOLALYTICS.COM 和 LOLALYTICS.COM-ARAM 的数据源导入后没有出装，符文页空白  v1.1.4版本

### ISSUE THREAD

**Issue by Skycandy1** [cangzhang/champ-r#87]
开发者您好，
  LOLALYTICS.COM 和 LOLALYTICS.COM-ARAM 的数据源导入后没有出装，符文页是空白  v1.1.4版本

![image](https://user-images.githubusercontent.com/35026954/132262952-d18fa72a-6432-4ddc-99e7-edbc9d9199e5.png)

**Comment by cangzhang** [comment]
别的数据源导入后可以看到出装吗？

**Comment by Skycandy1** [comment]
可以的，就这两个没有了

**Comment by cangzhang** [comment]
已修复, 大概 10min 之后可以看到

**Comment by Skycandy1** [comment]
好了， 辛苦啦~
