### ISSUE TITLE
11.18更新后 popup失效

### ISSUE THREAD

**Issue by magicwenli** [cangzhang/champ-r#88]
**Describe the bug 详细描述**

国服11.18更新后，天赋符文窗口无法正常弹出

**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**

 - OS: Windows 10 19042.1165
 - LOL Version: 11.18
 - Champ-r: v1.1.4-e116e5e

**Additional context 附加信息**

11.17出现过，但后来修复了。这次更新后也出现了这种情况。

**Comment by magicwenli** [comment]
好像是更新后的LCU客户端没有正常生成`英雄联盟\Game\Logs\LeagueClient Logs\`下的日志文件，所以Champ-r无法获取到正确的url和port.

**Comment by magicwenli** [comment]
#89 从`英雄联盟\LeagueClient\lockfile`获取port和password可以解决这个问题。

**Comment by cangzhang** [comment]
cool! 晚上我回去测试下

**Comment by sugarnine9** [comment]
> cool! 晚上我回去测试下

等待更新，不知道此次更新后还会不会再失效了，希望不会哈哈哈

**Comment by HYUOTFL** [comment]
> > cool! 晚上我回去测试下
> 
> 等待更新，不知道此次更新后还会不会再失效了，希望不会哈哈哈

怎么处理呢？上面说的获取什么东西的看不懂

**Comment by sugarnine9** [comment]
> > > cool! 晚上我回去测试下
> > 
> > 
> > 等待更新，不知道此次更新后还会不会再失效了，希望不会哈哈哈
> 
> 怎么处理呢？上面说的获取什么东西的看不懂

等作者更新吧

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.5

**Comment by bakamoon** [comment]
@cangzhang 需要卸载重装么？我直接覆盖更新还是无法添加装备和弹出天赋窗

**Comment by cangzhang** [comment]
> @cangzhang 需要卸载重装么？我直接覆盖更新还是无法添加装备和弹出天赋窗

不能看到装备说明目录选错了
