### ISSUE TITLE
有添加嚎哭深渊的配置打算吗

### ISSUE THREAD

**Issue by liusuanpaokafei** [cangzhang/champ-r#9]
老极地玩家了，导入配置后发现只有召唤师峡谷才能使用，，，作者大大有添加嚎哭深渊配置的打算吗

**Comment by 24540477zxc** [comment]
怪不得大乱斗没有，另外这个会和wegame冲突吗，我把wegame的关了

**Comment by cangzhang** [comment]
> 怪不得大乱斗没有，另外这个会和wegame冲突吗，我把wegame的关了

没有冲突

**Comment by cangzhang** [comment]
参见 #8
