### ISSUE TITLE
win11 安装没反应咋办

### ISSUE THREAD

**Issue by XiaoJiaRun** [cangzhang/champ-r#95]
**Describe the bug 详细描述**

**Screenshots or screen record 截图或录屏**

**Desktop (please complete the following information) 系统环境:**

**Additional context 附加信息**

**Comment by cangzhang** [comment]
请补充详细描述信息

**Comment by XiaoJiaRun** [comment]
就是下载之后，管理员打不开，没反应

**Comment by cangzhang** [comment]
可能是基础组件对 win11 还没有完全支持。之后会测试看看。

**Comment by cangzhang** [comment]
我试了 win11 最新 dev 版本是可以的
![image](https://user-images.githubusercontent.com/1357073/132974067-10478d8b-dd06-4e20-bdfd-c58068b0cfd7.png)
