### ISSUE TITLE
提个建议~关于系统通知

### ISSUE THREAD

**Issue by fengziX** [cangzhang/champ-r#98]
每次应用天赋以后,都会调用系统通知提示成功,
是否可以给一个开关来关闭系统提示呢?

**Comment by cangzhang** [comment]
后面会有计划把通知改成应用内通知。
你也可以暂时在 Windows 里把 ChampR 的通知关掉

**Comment by cangzhang** [comment]
https://github.com/cangzhang/champ-r/releases/tag/v1.1.9
